#!/bin/sh
#
# Copyright © 2011-2012 Martin Tournoij <martin@arp242.net>
# See below for full copyright
#
# https://code.arp242.net/pkg_sanity
#

usage()
{
	echo "Usage: ${0##*/} -o | -l | -u"
	echo ""
	echo "    -o    Check for binaries/libraries belonging to different FreeBSD versions"
	echo "          than what we're currently running"
	echo "    -l    Check for unresolvable shared libraries"
	echo "    -u    Check for files that don't seem to belong to any package in ${localbase}"
	echo ""
}

binaries()
{
	version=$(uname -r | head -c 1)
	bindirs="bin sbin"

	echo "===> Checking for old binaries"
	for d in ${bindirs}; do
		echo "${localbase}/${d}"

		for f in ${localbase}/${d}/*; do
			file "$f" | grep 'ELF' | grep -v "FreeBSD $version"
		done
	done
}

libraries()
{
	libdirs="/bin /sbin /libexec /lib /usr/bin /usr/sbin /usr/lib /usr/libexec \
	${localbase}/bin ${localbase}/sbin ${localbase}/lib ${localbase}/libexec"

	echo "===> Checking for unresolvable libraries"
	
	for d in ${libdirs}; do
		echo "Checking ${d}"
		for f in $(find ${d} -type f); do
			# TODO: Linux binaries are executed
			# http://www.freebsd.org/cgi/query-pr.cgi?pr=bin/127276
			check=$(ldd "${f}" 2>&1 | grep -v "not a dynamic" | grep "found")
			if [ $? -eq 0 ]; then
                pkgname=$(pkg_info -W ${f} | cut -d' ' -f6)
                echo "Found a problem in ${f} (Part of ${pkgname})"
				echo "${check}"
			fi
		done
	done
}

unowned()
{
	# Get list a files that should be installed
	pkgfiles_tmpfile=$(mktemp -t pkg_sanity)
	cat ${pkgdb}/*/+CONTENTS | grep -Ev '(^@|^\+)' | sort -u > "${pkgfiles_tmpfile}"
	pkgnum=$(wc -l "${pkgfiles_tmpfile}" | cut -d' ' -f 4)

	# Get a list of everything in /usr/local/
	files_tmpfile=$(mktemp -t pkg_sanity)
	find ${localbase} -type f -or -type l | sed "s|^${localbase}/||;" \
		| sort -u > ${files_tmpfile}
	filenum=$(wc -l "${files_tmpfile}" | cut -d' ' -f 4)

	# Let's diff!
	mising=$(diff -u00 ${pkgfiles_tmpfile} ${files_tmpfile} \
		| grep '^[-][^+-]' | sed "s|^-|${localbase}/|")
	unknown=$(diff -u00 ${pkgfiles_tmpfile} ${files_tmpfile} \
		| grep '^[+][^+-]' | sed "s|^\+|${localbase}/|")
	nummissing=$(echo "${missing}" | wc -l | cut -d' ' -f 4)
	numunknown=$(echo "${unknown}" | wc -l | cut -d' ' -f 4)

	# TODO: these numbers are off if you have linux- ports
	#echo "===> Files in pkgdb:       ${pkgnum}"
	#echo "===> Files in filesystem:  ${filenum}"
	#echo "===> Difference:          " $((${filenum} - ${pkgnum}))
	echo "===> Files that should be installed but are not: ${nummissing}"
	echo "${missing}"
	echo "===> Unknown files in ${localbase}: ${numunknown}"
	echo "${unknown}" | grep -v "${localbase}/etc/"

	rm "${files_tmpfile}" "${pkgfiles_tmpfile}"
}

pkgdb=${PKGDB:=/var/db/pkg}
localbase=${LOCALBASE:=/usr/local}

# Make sure localbase doesn't have a trailing slash
localbase=$(echo "${localbase}" | sed -e 's|//|/|g; s|/$||;')

while getopts "holu" arg; do
	case "${arg}" in
		h)	usage; exit 0 ;;
		o)	binaries=yes ;;
		l)	libraries=yes ;;
		u)	unowned=yes ;;
		*)	usage; exit 1 ;;
	esac
done

if [ -n "${binaries}" ]; then
	binaries
fi

if [ -n "${libraries}" ]; then
	libraries
fi

if [ -n "${unowned}" ]; then
	unowned
fi

if [ $# -eq 0 ]; then
	usage
	exit 1
fi


# The MIT License (MIT) 
# 
# Copyright © 2011-2012 Martin Tournoij
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.
